[package]
name = "mail_lansen"
version = "0.1.0"
edition = "2024"

[dependencies]
model = {path = "../model"}
lettre = { workspace = true }
sqlx = { workspace = true }
rocket = { workspace = true }
serde = {workspace = true}

